### ISSUE TITLE
Nice coursework

### ISSUE THREAD

**Issue by MorganREN** [ruotongding/Features_for_Estimating_AV_OpenCV#1]
Hope you can get a good mark!❤️

**Comment by ruotongding** [comment]
🐷



发自我的iPhone


------------------ Original ------------------
From: MorganREN ***@***.***&gt;
Date: Mon, Dec 20, 2021 10:15 PM
To: ruotongding/Features_for_Estimating_AV_OpenCV ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [ruotongding/Features_for_Estimating_AV_OpenCV] Nice coursework(Issue #1)





 
Hope you can get a good mark!❤️
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
